# Generated by Django 5.0.3 on 2025-11-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
