# Generated by Django 5.0.3 on 2026-01-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_indexes_and_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_per_user',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_trans_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='core_trans_amount_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='core_transa_uploade_4698db_idx',
            old_name='core_trans_file_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='core_transa_categor_cb6c70_idx',
            old_name='core_trans_cat_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='core_transa_uploade_0368b5_idx',
            old_name='core_trans_file_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='core_upload_user_id_68a3fa_idx',
            old_name='core_upload_user_id_uploaded_idx',
        ),
        migrations.RenameIndex(
            model_name='uploadedfile',
            new_name='core_upload_user_id_a859d0_idx',
            old_name='core_upload_user_id_file_hash_idx',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text='Comma-separated keywords for auto-categorization'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='content_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uploaded_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.uploadedfile'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('uploaded_file', 'content_hash'), name='unique_transaction_per_file'),
        ),
    ]
